# Generated by Django 6.0.7 on 2026-07-28 16:53

import data_access.mixins.sequence
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_ledger", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FiscalPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_period",
                    models.DateField(
                        help_text="Fecha o periodo fiscal inicial.",
                        verbose_name="Periodo Fiscal de Inicio",
                    ),
                ),
                (
                    "subsequent_period",
                    models.DateField(
                        blank=True,
                        help_text="Periodo fiscal subsecuente.",
                        null=True,
                        verbose_name="Periodo Fiscal Posterior",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preliminar", "Preliminar"),
                            ("procesado", "Procesado"),
                        ],
                        default="preliminar",
                        max_length=15,
                        verbose_name="Estatus del Periodo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiscal Period",
                "verbose_name_plural": "Fiscal Periods",
            },
        ),
        migrations.CreateModel(
            name="FiscalProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Legal Name or Corporate Name",
                    ),
                ),
                (
                    "rif",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_rif_format",
                                message="El RIF debe cumplir con el formato oficial venezolano (una letra [V, E, J, G, P, C] seguida de 8 a 9 dígitos numéricos sin guiones ni espacios).",
                                regex="^[VEJGPC]\\d{8,9}$",
                            )
                        ],
                        verbose_name="Fiscal Information Registry (RIF)",
                    ),
                ),
                (
                    "taxpayer_type",
                    models.CharField(
                        choices=[
                            ("FORMAL", "Formal"),
                            ("ORDINARY", "Ordinary"),
                            ("SPECIAL", "Special"),
                        ],
                        max_length=15,
                        verbose_name="Taxpayer Type",
                    ),
                ),
                (
                    "cxp_suppliers_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cuenta contable de pasivo comercial Cuentas por Pagar Proveedores.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="django_ledger.accountmodel",
                        verbose_name="Accounts Payable Suppliers Account",
                    ),
                ),
                (
                    "entity",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiscalprofile",
                        to="django_ledger.entitymodel",
                        verbose_name="entity model ledger",
                    ),
                ),
                (
                    "igtf_expense_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cuenta contable de gasto para IGTF Pagado en Compras.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="django_ledger.accountmodel",
                        verbose_name="IGTF Expense Account",
                    ),
                ),
                (
                    "initial_fiscal_period",
                    models.ForeignKey(
                        blank=True,
                        help_text="Periodo fiscal de inicio asignado a este perfil.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fiscal_profiles",
                        to="data_access.fiscalperiod",
                        verbose_name="Initial Fiscal Period",
                    ),
                ),
                (
                    "inventory_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cuenta contable de control para Inventario de Mercancía.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="django_ledger.accountmodel",
                        verbose_name="Inventory Account",
                    ),
                ),
                (
                    "islr_payable_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cuenta contable de pasivo para Retención de ISLR por Pagar.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="django_ledger.accountmodel",
                        verbose_name="ISLR Payable Account",
                    ),
                ),
                (
                    "ledger",
                    models.ForeignKey(
                        blank=True,
                        help_text="Libro Mayor General principal asignado a este perfil fiscal para el registro de asientos.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fiscal_profiles",
                        to="django_ledger.ledgermodel",
                        verbose_name="Principal Ledger Model",
                    ),
                ),
                (
                    "vat_credit_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cuenta contable de control para IVA Crédito Fiscal Computable.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="django_ledger.accountmodel",
                        verbose_name="VAT Credit Account",
                    ),
                ),
                (
                    "vat_withheld_payable_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cuenta contable de pasivo fiscal para IVA Retenido por Enterar al SENIAT.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="django_ledger.accountmodel",
                        verbose_name="VAT Withheld Payable Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiscal Profile",
                "verbose_name_plural": "Fiscal Profiles",
            },
        ),
        migrations.CreateModel(
            name="LocalSupplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=50,
                        verbose_name="Automatic Sequence Code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.MinLengthValidator(limit_value=1)
                        ],
                        verbose_name="Nombre del Proveedor",
                    ),
                ),
                (
                    "rif",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.MinLengthValidator(limit_value=1),
                            django.core.validators.RegexValidator(
                                code="invalid_supplier_rif",
                                message="El RIF debe comenzar estrictamente con una letra mayúscula válida (V, E, J, G, P, C) seguida de 8 a 9 dígitos numéricos, sin guiones ni espacios.",
                                regex="^[VEJGPC]\\d{8,9}$",
                            ),
                        ],
                        verbose_name="Registro de Información Fiscal (RIF)",
                    ),
                ),
                (
                    "supplier_type",
                    models.CharField(
                        choices=[
                            ("WITH_RIF", "With RIF"),
                            ("WITHOUT_RIF", "Without RIF"),
                            ("NON_RESIDENT", "Non-Resident"),
                            ("NON_DOMICILED", "Non-Domiciled"),
                            ("NATURAL", "Natural Person"),
                        ],
                        default="WITH_RIF",
                        max_length=20,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                1, message="El campo no puede estar vacío."
                            )
                        ],
                        verbose_name="Supplier Type",
                    ),
                ),
                (
                    "vat_withholding_percentage",
                    models.DecimalField(
                        choices=[
                            (Decimal("0.00"), "0%"),
                            (Decimal("75.00"), "75%"),
                            (Decimal("100.00"), "100%"),
                        ],
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="VAT Withholding Percentage",
                    ),
                ),
                (
                    "ari_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="ARI Percentage (ISLR)",
                    ),
                ),
                (
                    "fiscal_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_models",
                        to="data_access.fiscalprofile",
                        verbose_name="Tenant / Associated Fiscal Profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Local Supplier",
                "verbose_name_plural": "Local Suppliers",
            },
            bases=(data_access.mixins.sequence.AutomaticCodeMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PurchaseLedgerInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("INVOICE", "Invoice"),
                            ("CREDIT_NOTE", "Credit Note"),
                            ("DEBIT_NOTE", "Debit Note"),
                        ],
                        default="INVOICE",
                        max_length=20,
                        verbose_name="Document Type",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El número de factura solo debe contener caracteres alfanuméricos estándar y guiones.",
                                regex="^[0-9A-Za-z\\-]+$",
                            )
                        ],
                        verbose_name="Document Number",
                    ),
                ),
                (
                    "invoice_control",
                    models.CharField(
                        max_length=50, verbose_name="Invoice Control Number"
                    ),
                ),
                ("date", models.DateField(verbose_name="Issue Date")),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Payment Date"
                    ),
                ),
                (
                    "application_month_year",
                    models.CharField(
                        max_length=7,
                        verbose_name="Application Month and Year (MM-YYYY)",
                    ),
                ),
                (
                    "purchase_type",
                    models.CharField(
                        choices=[("INTERNAL", "Internal"), ("IMPORT", "Import")],
                        default="INTERNAL",
                        max_length=20,
                        verbose_name="Purchase Type",
                    ),
                ),
                (
                    "import_form_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Import Form Number",
                    ),
                ),
                (
                    "import_file_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Import File Number",
                    ),
                ),
                (
                    "exempt_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Exempt Amount",
                    ),
                ),
                (
                    "taxable_base",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Taxable Base",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Sub Total",
                    ),
                ),
                (
                    "vat_percentage",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Alícuota General (16%)"),
                            (2, "Alícuota Reducida (8%)"),
                            (3, "Alícuota Adicional (31%)"),
                        ],
                        default=1,
                        verbose_name="General Tax Rate (%)",
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="VAT Amount",
                    ),
                ),
                (
                    "igtf_base",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="IGTF Base",
                    ),
                ),
                (
                    "igtf_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="IGTF Amount",
                    ),
                ),
                (
                    "total_purchase",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Total Purchase",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRELIMINARY", "Preliminary"),
                            ("PROCESSED", "Processed"),
                            ("ANULLED", "ANULLED"),
                        ],
                        default="PRELIMINARY",
                        max_length=15,
                        verbose_name="Invoice Status",
                    ),
                ),
                (
                    "invoicecategory",
                    models.CharField(
                        choices=[
                            (
                                "INVENTARIO",
                                "Adquisicion de mercancia para el inventario",
                            ),
                            ("BIENE", "Adquisicion de bienes (Gastos)"),
                            ("SERVICIO", "Adquisicion de servicio"),
                            (
                                "SERVICIO_MIXTO",
                                "Adquisicion de servicio bienes (Misma factura)",
                            ),
                        ],
                        default="INVENTARIO",
                        max_length=20,
                        verbose_name="Invoice category",
                    ),
                ),
                (
                    "affected_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_debit_notes",
                        to="data_access.purchaseledgerinvoice",
                        verbose_name="Affected Invoice (Credit/Debit Notes)",
                    ),
                ),
                (
                    "fiscal_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_models",
                        to="data_access.fiscalprofile",
                        verbose_name="Tenant / Associated Fiscal Profile",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_invoices",
                        to="data_access.localsupplier",
                        verbose_name="Local Supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Ledger Invoice",
                "verbose_name_plural": "Purchase Ledger Invoices",
            },
        ),
        migrations.CreateModel(
            name="IslrWithholdingCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        max_length=50, verbose_name="ISLR Document Number"
                    ),
                ),
                (
                    "application_date",
                    models.DateField(verbose_name="Fiscal Application Date"),
                ),
                (
                    "islr_withheld_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="ISLR Withheld Amount",
                    ),
                ),
                (
                    "subtracting",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Amount of the applied subtrahend",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRELIMINARY", "Preliminary"),
                            ("PROCESSED", "Processed"),
                        ],
                        default="PRELIMINARY",
                        max_length=15,
                        verbose_name="Invoice Status",
                    ),
                ),
                (
                    "concepts_payment_pnnr",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Honorarios Profesionales"),
                            (2, "Honorarios Prof. en Hipódromos"),
                            (3, "Honorarios Prof. en Centros de Salud"),
                            (4, "Comisiones Enajenación Inmuebles"),
                            (5, "Comisiones Mercantiles y Otras"),
                            (6, "Intereses Art. 27 # 2 L.I.S.L.R."),
                            (7, "Intereses"),
                            (8, "Exhibición de Películas. Art 27 # 15, y 34 LISLR"),
                            (9, "Regalías Art 27 # 16 LISLR"),
                            (10, "Asistencia Técnica Art 27 # 16 LISLR"),
                            (11, "Servicios Tecnológicos Art 27 # 16 LISLR"),
                            (12, "Ganancias en Juegos y Apuestas"),
                            (13, "Premios Lotería e Hipódromos Art. 62 LISLR"),
                            (
                                14,
                                "Propietarios de Animales de Carreras por Premios Recibidos",
                            ),
                            (15, "Servicios"),
                            (16, "Arrendamiento Bienes Inmuebles"),
                            (17, "Arrendamiento Bienes Muebles"),
                            (18, "Pagos de Tarjetas de Crédito o Consumo"),
                            (19, "Pagos por Adquisición de Fondos de Comercio"),
                            (
                                20,
                                "Enriquecimientos por Enajenación de Acciones en la Bolsa de Valores",
                            ),
                            (
                                21,
                                "Pagos por Enajenación de Acciones Fuera de la Bolsa de Valores",
                            ),
                        ],
                        help_text="Concepto de retención aplicable a personas naturales no residentes.",
                        null=True,
                        verbose_name="Concepto de Pago - Persona Natural No Residente (PNNR)",
                    ),
                ),
                (
                    "concepts_payment_pnr",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Honorarios Profesionales"),
                            (2, "Honorarios Prof. en Hipódromos"),
                            (3, "Honorarios Prof. en Centros de Salud"),
                            (4, "Comisiones Enajenación Inmuebles"),
                            (5, "Comisiones Mercantiles y Otras"),
                            (6, "Intereses"),
                            (7, "Ganancias en Juegos y Apuestas"),
                            (8, "Premios Lotería e Hipódromos Art. 62 LISLR"),
                            (
                                9,
                                "Propietarios de Animales de Carreras por Premios Recibidos",
                            ),
                            (10, "Servicios"),
                            (11, "Arrendamiento Bienes Inmuebles"),
                            (12, "Arrendamiento Bienes Muebles"),
                            (13, "Pagos de Tarjetas de Crédito o Consumo"),
                            (14, "Pago de Gasolina con Tarjeta de Crédito o Consumo"),
                            (15, "Fletes y Gastos de Transporte Nacional"),
                            (16, "Pago de Emp.de Seguro a Corredores"),
                            (
                                17,
                                "Pago de Empresas de Seguros por Reparación de Bienes de sus Asegurados",
                            ),
                            (
                                18,
                                "Pagos de Empresas de Seguro a Centros de Salud por Atención de sus Asegurados",
                            ),
                            (19, "Pagos por Adquisición de Fondos de Comercio"),
                            (20, "Publicidad y Propaganda"),
                            (
                                21,
                                "Enriquecimientos por Enajenación de Acciones en la Bolsa de Valores",
                            ),
                            (
                                22,
                                "Pagos por Enajenación de Acciones Fuera de la Bolsa de Valores",
                            ),
                        ],
                        help_text="Concepto de retención aplicable a personas naturales residentes.",
                        null=True,
                        verbose_name="Concepto de Pago - Persona Natural Residente (PNR)",
                    ),
                ),
                (
                    "concepts_payment_pjnd",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Honorarios Profesionales"),
                            (2, "Comisiones Enajenación Inmuebles"),
                            (3, "Comisiones Mercantiles y Otras"),
                            (4, "Intereses Art. 27 # 2 L.I.S.L.R."),
                            (5, "Intereses Art. 52 Parágrafo 2° L.I.S.L.R."),
                            (6, "Intereses"),
                            (7, "Agencias de Noticias Internacionales Art. 35 LISLR"),
                            (
                                8,
                                "Fletes y Gtos de Transp. Internacional (entre Venezuela y el Exterior o viceversa). Art. 36 LISLR",
                            ),
                            (
                                9,
                                "Fletes en el País a Emp. Internacional. Art. 36 LISLR",
                            ),
                            (10, "Exhibición de Películas. Art 27 # 15, y 34 LISLR"),
                            (11, "Regalías Art 27 # 16 LISLR"),
                            (12, "Asistencia Técnica Art 27 # 16 LISLR"),
                            (13, "Servicios Tecnológicos Art 27 # 16 LISLR"),
                            (
                                14,
                                "Primas de Seguro y Reaseg. Art. 27 #18 y Parágrafo 3° Art. 52 LISLR",
                            ),
                            (15, "Ganancias en Juegos y Apuestas"),
                            (16, "Premios Lotería e Hipódromos Art. 62 LISLR"),
                            (
                                17,
                                "Propietarios de Animales de Carreras por Premios Recibidos",
                            ),
                            (18, "Servicios"),
                            (19, "Arrendamiento Bienes Inmuebles"),
                            (20, "Arrendamiento Bienes Muebles"),
                            (21, "Pagos de Tarjetas de Crédito o Consumo"),
                            (22, "Pagos por Adquisición de Fondos de Comercio"),
                            (23, "Publicidad y Propaganda"),
                            (
                                24,
                                "Enriquecimientos por Enajenación de Acciones en la Bolsa de Valores",
                            ),
                            (
                                25,
                                "Pagos por Enajenación de Acciones Fuera de la Bolsa de Valores",
                            ),
                        ],
                        help_text="Concepto de retención aplicable a personas jurídicas no domiciliadas.",
                        null=True,
                        verbose_name="Concepto de Pago - Persona Jurídica No Residente (PJNR)",
                    ),
                ),
                (
                    "concepts_payment_pjd",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Honorarios Profesionales"),
                            (2, "Comisiones Enajenación Inmuebles"),
                            (3, "Comisiones Mercantiles y Otras"),
                            (4, "Intereses"),
                            (5, "Ganancias en Juegos y Apuestas"),
                            (6, "Premios Lotería e Hipódromos Art. 62 LISLR"),
                            (
                                7,
                                "Propietarios de Animales de Carreras por Premios Recibidos",
                            ),
                            (8, "Servicios"),
                            (9, "Arrendamiento Bienes Inmuebles"),
                            (10, "Arrendamiento Bienes Muebles"),
                            (11, "Pagos de Tarjetas de Crédito o Consumo"),
                            (12, "Pago de Gasolina con Tarjeta de Crédito o Consumo"),
                            (13, "Fletes y Gastos de Transporte Nacional"),
                            (14, "Pago de Emp.de Seguro a Corredores"),
                            (
                                15,
                                "Pago de Empresas de Seguros por Reparación de Bienes de sus Asegurados",
                            ),
                            (
                                16,
                                "Pagos de Empresas de Seguro a Centros de Salud por Atención de sus Asegurados",
                            ),
                            (17, "Pagos por Adquisición de Fondos de Comercio"),
                            (18, "Publicidad y Propaganda"),
                            (19, "Publicidad y Propaganda Emisoras de Radio"),
                            (
                                20,
                                "Enriquecimientos por Enajenación de Acciones en la Bolsa de Valores",
                            ),
                            (
                                21,
                                "Pagos por Enajenación de Acciones Fuera de la Bolsa de Valores",
                            ),
                        ],
                        help_text="Concepto de retención aplicable a personas jurídicas domiciliadas.",
                        null=True,
                        verbose_name="Concepto de Pago - Persona Jurídica Residente (PJR)",
                    ),
                ),
                (
                    "fiscal_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_models",
                        to="data_access.fiscalprofile",
                        verbose_name="Tenant / Associated Fiscal Profile",
                    ),
                ),
                (
                    "purchase_invoice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="islr_withholding_certificates",
                        to="data_access.purchaseledgerinvoice",
                        verbose_name="Related Purchase Invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "ISLR Withholding Certificate",
                "verbose_name_plural": "ISLR Withholding Certificates",
            },
        ),
        migrations.CreateModel(
            name="VatWithholdingCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_date",
                    models.DateField(verbose_name="Fiscal Application Date"),
                ),
                (
                    "vat_withholding_percentage",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "75 %"), (2, "100 %")],
                        default=1,
                        verbose_name="VAT Withholding Percentage (%)",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        max_length=50, verbose_name="Withholding Document Number"
                    ),
                ),
                (
                    "vat_withheld_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="VAT Withheld Amount",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRELIMINARY", "Preliminary"),
                            ("PROCESSED", "Processed"),
                        ],
                        default="PRELIMINARY",
                        max_length=15,
                        verbose_name="Invoice Status",
                    ),
                ),
                (
                    "fiscal_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_models",
                        to="data_access.fiscalprofile",
                        verbose_name="Tenant / Associated Fiscal Profile",
                    ),
                ),
                (
                    "purchase_invoice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vat_withholding_certificate",
                        to="data_access.purchaseledgerinvoice",
                        verbose_name="Associated Purchase Invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "VAT Withholding Certificate",
                "verbose_name_plural": "VAT Withholding Certificates",
            },
        ),
        migrations.AddConstraint(
            model_name="fiscalprofile",
            constraint=models.UniqueConstraint(
                fields=("rif",), name="data_access_fiscalprofile_unique_rif"
            ),
        ),
        migrations.AddConstraint(
            model_name="fiscalprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("name", ""), _negated=True),
                name="data_access_fiscalprofile_name_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="fiscalprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("rif", ""), _negated=True),
                name="data_access_fiscalprofile_rif_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="localsupplier",
            constraint=models.UniqueConstraint(
                fields=("fiscal_profile", "rif"),
                name="data_access_localsupplier_unique_profile_rif",
            ),
        ),
        migrations.AddConstraint(
            model_name="localsupplier",
            constraint=models.UniqueConstraint(
                fields=("fiscal_profile", "code"),
                name="data_access_localsupplier_unique_profile_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="localsupplier",
            constraint=models.CheckConstraint(
                condition=models.Q(("name", ""), _negated=True),
                name="data_access_localsupplier_name_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="localsupplier",
            constraint=models.CheckConstraint(
                condition=models.Q(("rif", ""), _negated=True),
                name="data_access_localsupplier_rif_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="localsupplier",
            constraint=models.CheckConstraint(
                condition=models.Q(("code", ""), _negated=True),
                name="data_access_localsupplier_code_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="localsupplier",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ari_percentage__isnull", True),
                    models.Q(("ari_percentage__gte", 0), ("ari_percentage__lte", 100)),
                    _connector="OR",
                ),
                name="data_access_localsupplier_ari_percentage_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseledgerinvoice",
            constraint=models.UniqueConstraint(
                fields=("supplier", "number", "document_type", "fiscal_profile"),
                name="unique_supplier_invoice_document",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseledgerinvoice",
            constraint=models.UniqueConstraint(
                fields=(
                    "supplier",
                    "invoice_control",
                    "document_type",
                    "fiscal_profile",
                ),
                name="unique_supplier_control_document",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseledgerinvoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("exempt_amount__gte", 0)),
                name="purchase_invoice_exempt_amount_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseledgerinvoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("taxable_base__gte", 0)),
                name="purchase_invoice_taxable_base_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseledgerinvoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("vat_amount__gte", 0)),
                name="purchase_invoice_vat_amount_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseledgerinvoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("igtf_amount__gte", 0)),
                name="purchase_invoice_igtf_amount_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseledgerinvoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("purchase_type", "IMPORT"), _negated=True),
                    models.Q(
                        ("import_form_number__isnull", False),
                        ("import_file_number__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="purchase_invoice_import_fields_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseledgerinvoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("document_type", "INVOICE"),
                    ("affected_invoice__isnull", False),
                    _connector="OR",
                ),
                name="purchase_invoice_notes_affected_invoice_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="islrwithholdingcertificate",
            constraint=models.UniqueConstraint(
                fields=("document_number", "fiscal_profile"),
                name="unique_document_per_fiscal_profile",
            ),
        ),
        migrations.AddConstraint(
            model_name="vatwithholdingcertificate",
            constraint=models.UniqueConstraint(
                fields=("fiscal_profile", "document_number"),
                name="unique_withholding_per_fiscal_profile",
            ),
        ),
        migrations.AddConstraint(
            model_name="vatwithholdingcertificate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("application_date__lte", django.db.models.functions.datetime.Now())
                ),
                name="withholding_date_not_future",
            ),
        ),
    ]
