# Generated by Django 6.0.5 on 2026-06-16 18:22

import data_access.models.supplier
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_ledger", "0029_stagedtransactionmodel_matched_transaction_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FiscalProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Internal Control Code"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=35, verbose_name="Legal Name or Corporate Name"
                    ),
                ),
                (
                    "rif",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        verbose_name="Fiscal Information Registry (RIF)",
                    ),
                ),
                (
                    "nit",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Tax Identification Number (NIT)",
                    ),
                ),
                (
                    "taxpayer_type",
                    models.CharField(
                        choices=[
                            ("FORMAL", "Formal"),
                            ("ORDINARY", "Ordinary"),
                            ("SPECIAL", "Special"),
                        ],
                        max_length=15,
                        verbose_name="Taxpayer Type",
                    ),
                ),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fiscal_profile",
                        to="django_ledger.entitymodel",
                        verbose_name="Django Ledger Entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiscal Profile",
                "verbose_name_plural": "Fiscal Profiles",
            },
        ),
        migrations.CreateModel(
            name="LocalSupplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, verbose_name="Supplier Code")),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Name or Corporate Name"
                    ),
                ),
                (
                    "rif",
                    models.CharField(
                        max_length=20, verbose_name="Fiscal Information Registry (RIF)"
                    ),
                ),
                (
                    "supplier_type",
                    models.CharField(
                        choices=[
                            ("WITH_RIF", "With RIF"),
                            ("WITHOUT_RIF", "Without RIF"),
                            ("NON_RESIDENT", "Non-Resident"),
                            ("NON_DOMICILED", "Non-Domiciled"),
                        ],
                        max_length=20,
                        verbose_name="Supplier Type",
                    ),
                ),
                (
                    "usual_withholding",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Usual Withholding Concept",
                    ),
                ),
                (
                    "vat_withholding_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            data_access.models.supplier.validate_vat_withholding_percentage
                        ],
                        verbose_name="VAT Withholding Percentage",
                    ),
                ),
                (
                    "ari_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="ARI Percentage (ISLR)",
                    ),
                ),
                (
                    "fiscal_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="local_suppliers",
                        to="data_access.fiscalprofile",
                        verbose_name="Fiscal Profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Local Supplier",
                "verbose_name_plural": "Local Suppliers",
                "unique_together": {("fiscal_profile", "rif")},
            },
        ),
        migrations.CreateModel(
            name="PurchaseLedgerInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("INVOICE", "Invoice"),
                            ("CREDIT_NOTE", "Credit Note"),
                            ("DEBIT_NOTE", "Debit Note"),
                        ],
                        default="INVOICE",
                        max_length=20,
                        verbose_name="Document Type",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=50, verbose_name="Document Number"),
                ),
                (
                    "invoice_control",
                    models.CharField(
                        max_length=50, verbose_name="Invoice Control Number"
                    ),
                ),
                ("date", models.DateField(verbose_name="Issue Date")),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Payment Date"
                    ),
                ),
                (
                    "application_month_year",
                    models.CharField(
                        max_length=7,
                        verbose_name="Application Month and Year (MM-YYYY)",
                    ),
                ),
                (
                    "purchase_type",
                    models.CharField(
                        choices=[("INTERNAL", "Internal"), ("IMPORT", "Import")],
                        default="INTERNAL",
                        max_length=20,
                        verbose_name="Purchase Type",
                    ),
                ),
                (
                    "import_form_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Import Form Number",
                    ),
                ),
                (
                    "import_file_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Import File Number",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(max_length=50, verbose_name="Transaction Type"),
                ),
                (
                    "affected_invoice",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Affected Invoice (Credit/Debit Notes)",
                    ),
                ),
                (
                    "tax_credit_type",
                    models.CharField(max_length=50, verbose_name="Tax Credit Type"),
                ),
                (
                    "vat_withholding_accounting_mapping",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="VAT Withholding Accounting Mapping",
                    ),
                ),
                (
                    "exempt_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Exempt Amount",
                    ),
                ),
                (
                    "taxable_base",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Taxable Base",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Sub Total",
                    ),
                ),
                (
                    "general_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("16.00"),
                        max_digits=5,
                        verbose_name="General Tax Rate (%)",
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="VAT Amount",
                    ),
                ),
                (
                    "igtf_base",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="IGTF Base",
                    ),
                ),
                (
                    "igtf_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="IGTF Amount",
                    ),
                ),
                (
                    "total_purchase",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Total Purchase",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRELIMINARY", "Preliminary"),
                            ("PROCESSED", "Processed"),
                        ],
                        default="PRELIMINARY",
                        max_length=15,
                        verbose_name="Invoice Status",
                    ),
                ),
                (
                    "fiscal_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modules",
                        to="data_access.fiscalprofile",
                        verbose_name="Tenant / Associated Fiscal Profile",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_invoices",
                        to="data_access.localsupplier",
                        verbose_name="Local Supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Invoice (Ledger)",
                "verbose_name_plural": "Purchase Invoices (Ledger)",
            },
        ),
        migrations.CreateModel(
            name="PurchaseInvoiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=255, verbose_name="Item/Service Description"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Unit Price"
                    ),
                ),
                (
                    "units",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="Units"
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Discount Percentage (%)",
                    ),
                ),
                (
                    "subtotal_before_vat",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Subtotal before VAT",
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="VAT Rate (%)"
                    ),
                ),
                (
                    "line_vat_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Line VAT Amount"
                    ),
                ),
                (
                    "nature",
                    models.CharField(
                        choices=[("GOOD", "Good"), ("SERVICE", "Service")],
                        max_length=10,
                        verbose_name="Line Nature",
                    ),
                ),
                (
                    "applies_islr_withholding",
                    models.BooleanField(
                        default=False, verbose_name="Applies ISLR Withholding?"
                    ),
                ),
                (
                    "islr_withholding_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="ISLR Withholding Percentage (%)",
                    ),
                ),
                (
                    "vectorize_description",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Descriptive Text for Semantic Processing / Embeddings",
                    ),
                ),
                (
                    "accounting_mapping",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Expense/Inventory Accounting Mapping",
                    ),
                ),
                (
                    "purchase_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="data_access.purchaseledgerinvoice",
                        verbose_name="Associated Purchase Invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Invoice Line",
                "verbose_name_plural": "Purchase Invoice Lines",
            },
        ),
        migrations.CreateModel(
            name="IslrWithholdingCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(
                        max_length=50, verbose_name="ISLR Certificate Number"
                    ),
                ),
                (
                    "closing_day_month",
                    models.CharField(max_length=10, verbose_name="Closing Day/Month"),
                ),
                (
                    "line_taxable_base",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Line Taxable Base",
                    ),
                ),
                (
                    "applied_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Applied Rate (%)"
                    ),
                ),
                (
                    "islr_withheld_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="ISLR Withheld Amount",
                    ),
                ),
                (
                    "fiscal_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modules",
                        to="data_access.fiscalprofile",
                        verbose_name="Tenant / Associated Fiscal Profile",
                    ),
                ),
                (
                    "source_line",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="islr_withholding_certificate",
                        to="data_access.purchaseinvoiceline",
                        verbose_name="Source Invoice Line",
                    ),
                ),
                (
                    "purchase_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="islr_withholding_certificates",
                        to="data_access.purchaseledgerinvoice",
                        verbose_name="Related Purchase Invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "ISLR Withholding Certificate",
                "verbose_name_plural": "ISLR Withholding Certificates",
            },
        ),
        migrations.CreateModel(
            name="VatWithholdingCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_date",
                    models.DateField(verbose_name="Fiscal Application Date"),
                ),
                (
                    "vat_withholding_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="VAT Withholding Percentage (%)",
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        verbose_name="Withholding Certificate Number",
                    ),
                ),
                (
                    "vat_withheld_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="VAT Withheld Amount",
                    ),
                ),
                (
                    "fiscal_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modules",
                        to="data_access.fiscalprofile",
                        verbose_name="Tenant / Associated Fiscal Profile",
                    ),
                ),
                (
                    "purchase_invoice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vat_withholding_certificate",
                        to="data_access.purchaseledgerinvoice",
                        verbose_name="Associated Purchase Invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "VAT Withholding Certificate",
                "verbose_name_plural": "VAT Withholding Certificates",
            },
        ),
    ]
