# Generated by Django 6.0.5 on 2026-07-13 18:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_access", "0001_initial"),
        ("django_ledger", "0029_stagedtransactionmodel_matched_transaction_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="fiscalprofile",
            name="data_access_fiscalprofile_code_not_empty",
        ),
        migrations.RemoveField(
            model_name="localsupplier",
            name="usual_withholding",
        ),
        migrations.AlterField(
            model_name="fiscalprofile",
            name="name",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                verbose_name="Legal Name or Corporate Name",
            ),
        ),
        migrations.AlterField(
            model_name="fiscalprofile",
            name="rif",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_rif_format",
                        message="El RIF debe cumplir con el formato oficial venezolano (una letra [V, E, J, G, P, C] seguida de 8 a 9 dígitos numéricos sin guiones ni espacios).",
                        regex="^[VEJGPC]\\d{8,9}$",
                    )
                ],
                verbose_name="Fiscal Information Registry (RIF)",
            ),
        ),
        migrations.AlterField(
            model_name="localsupplier",
            name="ari_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
                verbose_name="ARI Percentage (ISLR)",
            ),
        ),
        migrations.AlterField(
            model_name="localsupplier",
            name="rif",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.MinLengthValidator(limit_value=1),
                    django.core.validators.RegexValidator(
                        code="invalid_supplier_rif",
                        message="El RIF debe comenzar estrictamente con una letra mayúscula válida (V, E, J, G, P, C) seguida de 8 a 9 dígitos numéricos, sin guiones ni espacios.",
                        regex="^[VEJGPC]\\d{8,9}$",
                    ),
                ],
                verbose_name="Registro de Información Fiscal (RIF)",
            ),
        ),
        migrations.AlterField(
            model_name="localsupplier",
            name="supplier_type",
            field=models.CharField(
                choices=[
                    ("WITH_RIF", "With RIF"),
                    ("WITHOUT_RIF", "Without RIF"),
                    ("NON_RESIDENT", "Non-Resident"),
                    ("NON_DOMICILED", "Non-Domiciled"),
                    ("NATURAL", "Natural Person"),
                ],
                default="WITH_RIF",
                max_length=20,
                validators=[
                    django.core.validators.MinLengthValidator(
                        1, message="El campo no puede estar vacío."
                    )
                ],
                verbose_name="Supplier Type",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseledgerinvoice",
            name="number",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El número de factura solo debe contener caracteres alfanuméricos estándar y guiones.",
                        regex="^[0-9A-Za-z\\-]+$",
                    )
                ],
                verbose_name="Document Number",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseledgerinvoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("PRELIMINARY", "Preliminary"),
                    ("PROCESSED", "Processed"),
                    ("ANULLED", "ANULLED"),
                ],
                default="PRELIMINARY",
                max_length=15,
                verbose_name="Invoice Status",
            ),
        ),
        migrations.AddConstraint(
            model_name="fiscalprofile",
            constraint=models.UniqueConstraint(
                fields=("rif",), name="data_access_fiscalprofile_unique_rif"
            ),
        ),
        migrations.AddConstraint(
            model_name="localsupplier",
            constraint=models.CheckConstraint(
                condition=models.Q(("code", ""), _negated=True),
                name="data_access_localsupplier_code_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="localsupplier",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ari_percentage__isnull", True),
                    models.Q(("ari_percentage__gte", 0), ("ari_percentage__lte", 100)),
                    _connector="OR",
                ),
                name="data_access_localsupplier_ari_percentage_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseledgerinvoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("purchase_type", "IMPORT"), _negated=True),
                    models.Q(
                        ("import_form_number__isnull", False),
                        ("import_file_number__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="purchase_invoice_import_fields_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseledgerinvoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("document_type", "INVOICE"),
                    ("affected_invoice__isnull", False),
                    _connector="OR",
                ),
                name="purchase_invoice_notes_affected_invoice_required",
            ),
        ),
        migrations.RemoveField(
            model_name="fiscalprofile",
            name="code",
        ),
        migrations.RemoveField(
            model_name="fiscalprofile",
            name="nit",
        ),
        migrations.RemoveField(
            model_name="fiscalprofile",
            name="ut",
        ),
    ]
