# Generated by Django 6.0.5 on 2026-06-19 03:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_access", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="localsupplier",
            unique_together={("fiscal_profile", "rif")},
        ),
        migrations.AddField(
        model_name="islrwithholdingcertificate",
        name="document_number",
        field=models.CharField(
            blank=True,
            editable=False,
            max_length=50,
            verbose_name="ISLR Document Number",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="islrwithholdingcertificate",
            unique_together={("fiscal_profile", "document_number")},
        ),
        migrations.AddField(
            model_name="vatwithholdingcertificate",
            name="document_number",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=50,
                verbose_name="Withholding Document Number",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vatwithholdingcertificate",
            unique_together={("fiscal_profile", "document_number")},
        ),
        migrations.AddField(
            model_name="purchaseledgerinvoice",
            name="code",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=50,
                verbose_name="Automatic Sequence Code",
            ),
        ),
        migrations.AlterField(
            model_name="islrwithholdingcertificate",
            name="fiscal_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_models",
                to="data_access.fiscalprofile",
                verbose_name="Tenant / Associated Fiscal Profile",
            ),
        ),
        migrations.AlterField(
            model_name="localsupplier",
            name="code",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=50,
                verbose_name="Automatic Sequence Code",
            ),
        ),
        migrations.AlterField(
            model_name="localsupplier",
            name="fiscal_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_models",
                to="data_access.fiscalprofile",
                verbose_name="Tenant / Associated Fiscal Profile",
            ),
        ),
        migrations.AlterField(
            model_name="localsupplier",
            name="supplier_type",
            field=models.CharField(
                choices=[
                    ("WITH_RIF", "With RIF"),
                    ("WITHOUT_RIF", "Without RIF"),
                    ("NON_RESIDENT", "Non-Resident"),
                    ("NON_DOMICILED", "Non-Domiciled"),
                ],
                max_length=20,
                validators=[
                    django.core.validators.MinLengthValidator(
                        1, message="El campo no puede estar vacío."
                    )
                ],
                verbose_name="Supplier Type",
            ),
        ),
        migrations.AlterField(
            model_name="localsupplier",
            name="vat_withholding_percentage",
            field=models.DecimalField(
                choices=[
                    (Decimal("0.00"), "0%"),
                    (Decimal("75.00"), "75%"),
                    (Decimal("100.00"), "100%"),
                ],
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                verbose_name="VAT Withholding Percentage",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseledgerinvoice",
            name="fiscal_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_models",
                to="data_access.fiscalprofile",
                verbose_name="Tenant / Associated Fiscal Profile",
            ),
        ),
        migrations.AlterField(
            model_name="vatwithholdingcertificate",
            name="fiscal_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_models",
                to="data_access.fiscalprofile",
                verbose_name="Tenant / Associated Fiscal Profile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="localsupplier",
            unique_together={("fiscal_profile", "code"), ("fiscal_profile", "rif")},
        ),
        migrations.AlterUniqueTogether(
            name="purchaseledgerinvoice",
            unique_together={("fiscal_profile", "code")},
        ),
        migrations.RemoveField(
            model_name="islrwithholdingcertificate",
            name="certificate_number",
        ),
        migrations.RemoveField(
            model_name="vatwithholdingcertificate",
            name="certificate_number",
        ),
    ]
