# Generated by Django 6.0.7 on 2026-08-02 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_access", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="islrwithholdingcertificate",
            name="fiscal_period",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fiscal Period(DD-MM-YYYY)"
            ),
        ),
        migrations.AddField(
            model_name="purchaseledgerinvoice",
            name="fiscal_period",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fiscal Period(DD-MM-YYYY)"
            ),
        ),
        migrations.AddField(
            model_name="vatwithholdingcertificate",
            name="fiscal_period",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fiscal Period(DD-MM-YYYY)"
            ),
        ),
    ]
