# Generated by Django 6.0.7 on 2026-08-04 02:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_access", "0002_islrwithholdingcertificate_fiscal_period_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseledgerinvoice",
            name="amount_exonerated",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Amount exonerated",
            ),
        ),
        migrations.AddField(
            model_name="purchaseledgerinvoice",
            name="amount_not_subject",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Amount not subject",
            ),
        ),
        migrations.AddField(
            model_name="purchaseledgerinvoice",
            name="amount_without_right_to_credit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Amount without right to credit",
            ),
        ),
        migrations.AddField(
            model_name="purchaseledgerinvoice",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("01 Registro", "Registro"),
                    ("02 Complemento", "Complemento"),
                    ("03 Anulación", "Anulacion"),
                    ("04 Ajuste", "Ajuste"),
                ],
                default="01 Registro",
                max_length=20,
                verbose_name="transaction type",
            ),
        ),
    ]
