# Generated by Django 6.0.5 on 2026-07-15 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "data_access",
            "0002_remove_fiscalprofile_data_access_fiscalprofile_code_not_empty_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseledgerinvoice",
            name="transaction_type",
        ),
    ]
