# Generated by Django 6.0.5 on 2026-06-19 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_access", "0002_alter_localsupplier_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="localsupplier",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="localsupplier",
            name="name",
            field=models.CharField(
                max_length=255,
                validators=[django.core.validators.MinLengthValidator(limit_value=1)],
                verbose_name="Nombre del Proveedor",
            ),
        ),
        migrations.AlterField(
            model_name="localsupplier",
            name="rif",
            field=models.CharField(
                max_length=20,
                validators=[django.core.validators.MinLengthValidator(limit_value=1)],
                verbose_name="Registro de Información Fiscal (RIF)",
            ),
        ),
        migrations.AlterField(
            model_name="localsupplier",
            name="supplier_type",
            field=models.CharField(
                choices=[
                    ("WITH_RIF", "With RIF"),
                    ("WITHOUT_RIF", "Without RIF"),
                    ("NON_RESIDENT", "Non-Resident"),
                    ("NON_DOMICILED", "Non-Domiciled"),
                ],
                default="WITH_RIF",
                max_length=20,
                validators=[
                    django.core.validators.MinLengthValidator(
                        1, message="El campo no puede estar vacío."
                    )
                ],
                verbose_name="Supplier Type",
            ),
        ),
        migrations.AddConstraint(
            model_name="localsupplier",
            constraint=models.UniqueConstraint(
                fields=("fiscal_profile", "rif"),
                name="data_access_localsupplier_unique_profile_rif",
            ),
        ),
        migrations.AddConstraint(
            model_name="localsupplier",
            constraint=models.UniqueConstraint(
                fields=("fiscal_profile", "code"),
                name="data_access_localsupplier_unique_profile_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="localsupplier",
            constraint=models.CheckConstraint(
                condition=models.Q(("name", ""), _negated=True),
                name="data_access_localsupplier_name_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="localsupplier",
            constraint=models.CheckConstraint(
                condition=models.Q(("rif", ""), _negated=True),
                name="data_access_localsupplier_rif_not_empty",
            ),
        ),
    ]
