# Generated by Django 6.0.5 on 2026-07-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_access", "0003_remove_purchaseledgerinvoice_transaction_type"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="vatwithholdingcertificate",
            name="valid_withholding_percentages",
        ),
        migrations.AlterField(
            model_name="vatwithholdingcertificate",
            name="vat_withheld_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                verbose_name="VAT Withheld Amount",
            ),
        ),
    ]
