# Generated by Django 6.0.5 on 2026-06-23 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_access", "0003_alter_localsupplier_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fiscalprofile",
            name="entity",
        ),
    ]
