# Generated by Django 6.0.7 on 2026-08-11 01:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_access", "0003_purchaseledgerinvoice_amount_exonerated_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="localsupplier",
            name="data_access_localsupplier_unique_profile_code",
        ),
        migrations.RemoveConstraint(
            model_name="localsupplier",
            name="data_access_localsupplier_code_not_empty",
        ),
        migrations.RemoveConstraint(
            model_name="purchaseledgerinvoice",
            name="unique_supplier_invoice_document",
        ),
        migrations.AlterField(
            model_name="purchaseledgerinvoice",
            name="invoice_control",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El número de factura solo debe contener caracteres alfanuméricos estándar y guiones.",
                        regex="^[0-9A-Za-z\\-]+$",
                    )
                ],
                verbose_name="Invoice Control Number",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseledgerinvoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("PRELIMINARY", "Preliminary"),
                    ("PROCESSED", "Processed"),
                    ("ANULLED", "ANULLED"),
                    ("ANULLED_PROCESSED", "ANULLED_PROCESSED"),
                ],
                default="PRELIMINARY",
                max_length=20,
                verbose_name="Invoice Status",
            ),
        ),
        migrations.RemoveField(
            model_name="localsupplier",
            name="code",
        ),
        migrations.RemoveField(
            model_name="purchaseledgerinvoice",
            name="application_month_year",
        ),
        migrations.RemoveField(
            model_name="purchaseledgerinvoice",
            name="payment_date",
        ),
    ]
