# Generated by Django 6.0.5 on 2026-07-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "data_access",
            "0004_remove_vatwithholdingcertificate_valid_withholding_percentages_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="vatwithholdingcertificate",
            name="document_number",
            field=models.CharField(
                max_length=50, verbose_name="Withholding Document Number"
            ),
        ),
    ]
