# Generated by Django 6.0.7 on 2026-08-12 00:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "data_access",
            "0004_remove_localsupplier_data_access_localsupplier_unique_profile_code_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseledgerinvoice",
            name="igtf_base",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="IGTF Base",
            ),
        ),
    ]
