# Generated by Django 6.0.5 on 2026-06-29 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_access", "0004_remove_fiscalprofile_entity"),
        ("django_ledger", "0029_stagedtransactionmodel_matched_transaction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiscalprofile",
            name="entity",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fiscalprofile",
                to="django_ledger.entitymodel",
                verbose_name="entity model ledger",
            ),
        ),
    ]
