# Generated by Django 6.0.7 on 2026-08-17 01:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_access", "0005_alter_purchaseledgerinvoice_igtf_base"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseledgerinvoice",
            name="affected_account",
            field=models.JSONField(
                default=list, verbose_name="Cuentas de gasto imputadas"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseledgerinvoice",
            name="igtf_base",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="IGTF Base",
            ),
        ),
    ]
