# Generated by Django 6.0.5 on 2026-07-19 02:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_access", "0005_alter_vatwithholdingcertificate_document_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="islrwithholdingcertificate",
            name="document_number",
            field=models.CharField(max_length=50, verbose_name="ISLR Document Number"),
        ),
        migrations.AlterField(
            model_name="islrwithholdingcertificate",
            name="subtracting",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="Amount of the applied subtrahend",
            ),
        ),
    ]
