# Generated by Django 6.0.5 on 2026-06-29 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_access", "0005_fiscalprofile_entity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fiscalprofile",
            name="name",
        ),
    ]
