# Generated by Django 6.0.5 on 2026-07-19 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "data_access",
            "0006_alter_islrwithholdingcertificate_document_number_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="purchaseledgerinvoice",
            name="unique_purchase_invoice_profile_code",
        ),
        migrations.RemoveField(
            model_name="purchaseledgerinvoice",
            name="code",
        ),
    ]
