# Generated by Django 6.0.5 on 2026-06-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_access", "0006_remove_fiscalprofile_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiscalprofile",
            name="name",
            field=models.CharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="Legal Name or Corporate Name",
            ),
        ),
    ]
