# Generated by Django 6.0.7 on 2026-08-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_access", "0006_purchaseledgerinvoice_affected_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseledgerinvoice",
            name="deductibility",
            field=models.CharField(
                choices=[
                    ("Deducible", "Deducible"),
                    ("Parcialmente deducible", "Parcialmente Deducible"),
                    ("No deducible", "No Deducible"),
                ],
                default="Deducible",
                max_length=25,
                verbose_name="Deducibilidad del credito fiscal",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseledgerinvoice",
            name="invoicecategory",
            field=models.CharField(
                choices=[
                    ("INVENTARIO", "Adquisicion de mercancia para el inventario"),
                    ("BIENES", "Adquisicion de bienes (Gastos)"),
                    ("SERVICIO", "Adquisicion de servicio"),
                    (
                        "SERVICIO_MIXTO",
                        "Adquisicion de servicio bienes (Misma factura)",
                    ),
                ],
                default="INVENTARIO",
                max_length=20,
                verbose_name="Invoice category",
            ),
        ),
    ]
