# Generated by Django 6.0.7 on 2026-08-27 12:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_access", "0007_purchaseledgerinvoice_deductibility_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="islrwithholdingcertificate",
            name="service_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Valor del servicio al que aplicar los porcentajes de retención.",
                max_digits=15,
                verbose_name="Service Amount",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseledgerinvoice",
            name="affected_account",
            field=models.JSONField(
                blank=True,
                default=list,
                null=True,
                verbose_name="Cuentas de gasto imputadas",
            ),
        ),
    ]
