# Generated by Django 6.0.5 on 2026-07-02 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_access", "0007_fiscalprofile_name"),
        ("django_ledger", "0029_stagedtransactionmodel_matched_transaction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="islrwithholdingcertificate",
            name="fiscal_profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_models",
                to="data_access.fiscalprofile",
                verbose_name="Tenant / Associated Fiscal Profile",
            ),
        ),
        migrations.AlterField(
            model_name="localsupplier",
            name="fiscal_profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_models",
                to="data_access.fiscalprofile",
                verbose_name="Tenant / Associated Fiscal Profile",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseledgerinvoice",
            name="fiscal_profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_models",
                to="data_access.fiscalprofile",
                verbose_name="Tenant / Associated Fiscal Profile",
            ),
        ),
        migrations.AlterField(
            model_name="vatwithholdingcertificate",
            name="fiscal_profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_models",
                to="data_access.fiscalprofile",
                verbose_name="Tenant / Associated Fiscal Profile",
            ),
        ),
        migrations.AddConstraint(
            model_name="fiscalprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("name", ""), _negated=True),
                name="data_access_fiscalprofile_name_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="fiscalprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("rif", ""), _negated=True),
                name="data_access_fiscalprofile_rif_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="fiscalprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("code", ""), _negated=True),
                name="data_access_fiscalprofile_code_not_empty",
            ),
        ),
    ]
