# Generated by Django 6.0.5 on 2026-07-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "data_access",
            "0008_alter_islrwithholdingcertificate_fiscal_profile_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseinvoiceline",
            name="purchase_invoice",
        ),
        migrations.RemoveField(
            model_name="islrwithholdingcertificate",
            name="source_line",
        ),
        migrations.AlterModelOptions(
            name="purchaseledgerinvoice",
            options={
                "verbose_name": "Purchase Ledger Invoice",
                "verbose_name_plural": "Purchase Ledger Invoices",
            },
        ),
        migrations.AlterUniqueTogether(
            name="purchaseledgerinvoice",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="purchaseledgerinvoice",
            name="code",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Automatic Sequence Code"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseledgerinvoice",
            constraint=models.UniqueConstraint(
                fields=("supplier", "number", "document_type"),
                name="unique_supplier_invoice_document",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseledgerinvoice",
            constraint=models.UniqueConstraint(
                fields=("supplier", "invoice_control", "document_type"),
                name="unique_supplier_control_document",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseledgerinvoice",
            constraint=models.UniqueConstraint(
                fields=("fiscal_profile", "code"),
                name="unique_purchase_invoice_profile_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseledgerinvoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("exempt_amount__gte", 0)),
                name="purchase_invoice_exempt_amount_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseledgerinvoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("taxable_base__gte", 0)),
                name="purchase_invoice_taxable_base_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseledgerinvoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("vat_amount__gte", 0)),
                name="purchase_invoice_vat_amount_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseledgerinvoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("igtf_amount__gte", 0)),
                name="purchase_invoice_igtf_amount_not_negative",
            ),
        ),
        migrations.DeleteModel(
            name="PurchaseInvoiceLine",
        ),
    ]
