# Generated by Django 6.0.7 on 2026-09-01 23:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_access", "0009_alter_islrwithholdingcertificate_service_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="islrwithholdingcertificate",
            name="service_amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Valor del servicio al que aplicar los porcentajes de retención.",
                max_digits=15,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal("0.01"),
                        message="El monto del servicio debe ser mayor a cero.",
                    )
                ],
                verbose_name="Service Amount",
            ),
        ),
    ]
