# Generated by Django 6.0.5 on 2026-07-05 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_access", "0009_remove_purchaseinvoiceline_purchase_invoice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="islrwithholdingcertificate",
            name="fiscal_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_models",
                to="data_access.fiscalprofile",
                verbose_name="Tenant / Associated Fiscal Profile",
            ),
        ),
        migrations.AlterField(
            model_name="localsupplier",
            name="fiscal_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_models",
                to="data_access.fiscalprofile",
                verbose_name="Tenant / Associated Fiscal Profile",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseledgerinvoice",
            name="fiscal_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_models",
                to="data_access.fiscalprofile",
                verbose_name="Tenant / Associated Fiscal Profile",
            ),
        ),
        migrations.AlterField(
            model_name="vatwithholdingcertificate",
            name="fiscal_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_models",
                to="data_access.fiscalprofile",
                verbose_name="Tenant / Associated Fiscal Profile",
            ),
        ),
    ]
