# Generated by Django 6.0.7 on 2026-09-02 00:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_access", "0010_alter_islrwithholdingcertificate_service_amount"),
        ("django_ledger", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rif",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El RIF debe comenzar con V, E, J, G, P, C seguido de 8 a 9 dígitos.",
                                regex="^[VEJGPCvejgpc]\\d{8,9}$",
                            )
                        ],
                        verbose_name="RIF",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Nombre / Razón Social"
                    ),
                ),
                ("fiscal_address", models.TextField(verbose_name="Dirección Fiscal")),
                (
                    "phone_number",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El número de teléfono debe contener entre 10 y 11 dígitos.",
                                regex="^\\d{10,11}$",
                            )
                        ],
                        verbose_name="Teléfono",
                    ),
                ),
                (
                    "taxpayer_type",
                    models.CharField(
                        choices=[
                            ("ORDINARY", "Ordinario"),
                            ("SPECIAL", "Especial"),
                            ("NON_TAXPAYER", "No Contribuyente"),
                        ],
                        default="ORDINARY",
                        max_length=20,
                        verbose_name="Tipo de Contribuyente",
                    ),
                ),
                (
                    "custom_accounts_receivable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_receivable_accounts",
                        to="django_ledger.accountmodel",
                        verbose_name="Cuentas por Cobrar Comerciales",
                    ),
                ),
                (
                    "custom_income_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_income_accounts",
                        to="django_ledger.accountmodel",
                        verbose_name="Ventas de Mercancía General",
                    ),
                ),
                (
                    "fiscal_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_models",
                        to="data_access.fiscalprofile",
                        verbose_name="Tenant / Associated Fiscal Profile",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("rif",),
                        name="unique_active_rif_customer",
                        violation_error_message="Ya existe un registro activo con este número de RIF en la base de datos.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("rif", ""), _negated=True),
                            models.Q(("rif__regex", "^\\s+$"), _negated=True),
                        ),
                        name="customer_rif_not_empty",
                        violation_error_message="Este campo es obligatorio y no puede quedar vacío ni contener únicamente espacios.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("name", ""), _negated=True),
                            models.Q(("name__regex", "^\\s+$"), _negated=True),
                        ),
                        name="customer_name_not_empty",
                        violation_error_message="Este campo es obligatorio y no puede quedar vacío ni contener únicamente espacios.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("fiscal_address", ""), _negated=True),
                            models.Q(
                                ("fiscal_address__regex", "^\\s+$"), _negated=True
                            ),
                        ),
                        name="customer_fiscal_address_not_empty",
                        violation_error_message="Este campo es obligatorio y no puede quedar vacío ni contener únicamente espacios.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("phone_number", ""), _negated=True),
                            models.Q(("phone_number__regex", "^\\s+$"), _negated=True),
                        ),
                        name="customer_phone_number_not_empty",
                        violation_error_message="Este campo es obligatorio y no puede quedar vacío ni contener únicamente espacios.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("taxpayer_type", ""), _negated=True),
                            models.Q(("taxpayer_type__regex", "^\\s+$"), _negated=True),
                        ),
                        name="customer_taxpayer_type_not_empty",
                        violation_error_message="Este campo es obligatorio y no puede quedar vacío ni contener únicamente espacios.",
                    ),
                ],
            },
        ),
    ]
