# Generated by Django 6.0.5 on 2026-07-06 19:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "data_access",
            "0010_alter_islrwithholdingcertificate_fiscal_profile_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseledgerinvoice",
            name="affected_invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="credit_debit_notes",
                to="data_access.purchaseledgerinvoice",
                verbose_name="Affected Invoice (Credit/Debit Notes)",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseledgerinvoice",
            name="exempt_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Exempt Amount",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseledgerinvoice",
            name="taxable_base",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Taxable Base",
            ),
        ),
    ]
