# Generated by Django 6.0.5 on 2026-07-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_access", "0011_alter_purchaseledgerinvoice_affected_invoice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="islrwithholdingcertificate",
            name="status",
            field=models.CharField(
                choices=[("PRELIMINARY", "Preliminary"), ("PROCESSED", "Processed")],
                default="PRELIMINARY",
                max_length=15,
                verbose_name="Invoice Status",
            ),
        ),
        migrations.AddField(
            model_name="vatwithholdingcertificate",
            name="status",
            field=models.CharField(
                choices=[("PRELIMINARY", "Preliminary"), ("PROCESSED", "Processed")],
                default="PRELIMINARY",
                max_length=15,
                verbose_name="Invoice Status",
            ),
        ),
    ]
