# Generated by Django 6.0.7 on 2026-09-03 01:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_access", "0011_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_period", models.DateField(blank=True, null=True)),
                ("document_date", models.DateField()),
                ("invoice_number", models.CharField(blank=True, max_length=64)),
                ("last_receipt_number", models.CharField(blank=True, max_length=64)),
                ("document_number", models.CharField(blank=True, max_length=64)),
                (
                    "control_number",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Formato inválido de N° de Control.",
                                regex="^\\d{2}-\\d+$",
                            )
                        ],
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("INVOICE", "Factura"),
                            ("CREDIT_NOTE", "Nota de Crédito"),
                            ("DEBIT_NOTE", "Nota de Débito"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("01_REGISTER", "01 Registro"),
                            ("02_COMPLEMENT", "02 Complemento"),
                            ("03_ANNULMENT", "03 Anulación"),
                            ("04_ADJUSTMENT", "04 Ajuste"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "sale_type",
                    models.CharField(
                        choices=[("INTERNAL", "Interna"), ("EXPORT", "Exportación")],
                        max_length=20,
                    ),
                ),
                ("fiscal_printer_number", models.CharField(blank=True, max_length=64)),
                ("z_report_number", models.CharField(blank=True, max_length=64)),
                (
                    "record_status",
                    models.CharField(
                        choices=[
                            ("PRELIMINARY", "Preliminar"),
                            ("ANNULLED", "Anulado"),
                            ("PROCESSED", "Procesado"),
                            ("ANNULLED_PROCESSED", "Anulado Procesado"),
                        ],
                        default="PRELIMINARY",
                        max_length=20,
                    ),
                ),
                (
                    "total_sales_inc_vat",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "exempt_internal_sales",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "exonerated_internal_sales",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "non_subject_internal_sales",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "general_tax_base_16",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "general_tax_debit_16",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "reduced_tax_base_8",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "reduced_tax_debit_8",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "additional_tax_base_31",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "additional_tax_debit_31",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "igtf_tax_base",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "igtf_tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "fob_export_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "affected_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="data_access.salesrecord",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data_access.customer",
                    ),
                ),
                (
                    "fiscal_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_models",
                        to="data_access.fiscalprofile",
                        verbose_name="Tenant / Associated Fiscal Profile",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("fiscal_profile", "control_number", "document_type"),
                        name="unique_issued_document",
                        violation_error_message="Ya existe un documento registrado con este N° de Control y Tipo de Documento para el perfil fiscal actual.",
                    ),
                    models.UniqueConstraint(
                        fields=(
                            "fiscal_profile",
                            "fiscal_printer_number",
                            "z_report_number",
                        ),
                        name="unique_z_report",
                        violation_error_message="Este N° de Reporte Z ya fue registrado previamente para la máquina fiscal especificada.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("total_sales_inc_vat__gte", 0),
                            ("general_tax_base_16__gte", 0),
                        ),
                        name="positive_amounts",
                        violation_error_message="El monto total de la venta y las bases imponibles deben ser mayores o iguales a 0.00.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("last_receipt_number__gte", models.F("invoice_number")),
                            ("last_receipt_number", ""),
                            _connector="OR",
                        ),
                        name="valid_receipt_sequence",
                        violation_error_message="El número del último comprobante del día no puede ser menor al número del primer comprobante.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("transaction_type", "03_ANNULMENT"), _negated=True
                            ),
                            ("total_sales_inc_vat", 0),
                            _connector="OR",
                        ),
                        name="zero_amount_on_annulment",
                        violation_error_message="Las transacciones registradas como anulación requieren que la suma global de sus montos sea 0.00.",
                    ),
                ],
            },
        ),
    ]
