# Generated by Django 6.0.5 on 2026-07-07 16:49

import django.db.models.functions.datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_access", "0012_islrwithholdingcertificate_status_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vatwithholdingcertificate",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="vatwithholdingcertificate",
            constraint=models.UniqueConstraint(
                fields=("fiscal_profile", "document_number"),
                name="unique_withholding_per_fiscal_profile",
            ),
        ),
        migrations.AddConstraint(
            model_name="vatwithholdingcertificate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("application_date__lte", django.db.models.functions.datetime.Now())
                ),
                name="withholding_date_not_future",
            ),
        ),
        migrations.AddConstraint(
            model_name="vatwithholdingcertificate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "vat_withholding_percentage__in",
                        [Decimal("75.00"), Decimal("100.00")],
                    )
                ),
                name="valid_withholding_percentages",
            ),
        ),
    ]
