# Generated by Django 6.0.7 on 2026-09-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_access", "0012_salesrecord"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="salesrecord",
            name="unique_z_report",
        ),
        migrations.AddConstraint(
            model_name="salesrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("fiscal_printer_number", ""), _negated=True),
                    models.Q(("z_report_number", ""), _negated=True),
                ),
                fields=("fiscal_profile", "fiscal_printer_number", "z_report_number"),
                name="unique_z_report",
                violation_error_message="Este N° de Reporte Z ya fue registrado previamente para la máquina fiscal especificada.",
            ),
        ),
    ]
