# Generated by Django 6.0.7 on 2026-09-03 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_access", "0013_remove_salesrecord_unique_z_report_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="salesrecord",
            name="unique_z_report",
        ),
        migrations.AddConstraint(
            model_name="salesrecord",
            constraint=models.UniqueConstraint(
                fields=("fiscal_profile", "fiscal_printer_number", "z_report_number"),
                name="unique_z_report",
                violation_error_message="Este N° de Reporte Z ya fue registrado previamente para la máquina fiscal especificada.",
            ),
        ),
    ]
