# Generated by Django 6.0.7 on 2026-09-04 01:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_access", "0014_remove_salesrecord_unique_z_report_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="salesrecord",
            name="positive_amounts",
        ),
        migrations.RemoveConstraint(
            model_name="salesrecord",
            name="valid_receipt_sequence",
        ),
        migrations.RemoveConstraint(
            model_name="salesrecord",
            name="unique_z_report",
        ),
        migrations.AlterField(
            model_name="salesrecord",
            name="affected_invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="data_access.salesrecord",
            ),
        ),
        migrations.AlterField(
            model_name="salesrecord",
            name="control_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Formato inválido", regex="^\\s*\\d{2}-\\d+\\s*$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="salesrecord",
            name="document_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="salesrecord",
            name="document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INVOICE", "Factura"),
                    ("CREDIT_NOTE", "Nota de Crédito"),
                    ("DEBIT_NOTE", "Nota de Débito"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="salesrecord",
            name="fiscal_printer_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="salesrecord",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="salesrecord",
            name="last_receipt_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="salesrecord",
            name="record_status",
            field=models.CharField(
                choices=[
                    ("PRELIMINARY", "Preliminar"),
                    ("ANNULLED", "Anulado"),
                    ("PROCESSED", "Procesado"),
                    ("ANNULLED_PROCESSED", "Anulado_Procesado"),
                ],
                default="PRELIMINARY",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="salesrecord",
            name="z_report_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name="salesrecord",
            constraint=models.UniqueConstraint(
                fields=(
                    "fiscal_profile",
                    "fiscal_printer_number",
                    "z_report_number",
                    "invoice_number",
                    "last_receipt_number",
                ),
                name="unique_z_report",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("total_sales_inc_vat__gte", 0),
                    ("general_tax_base_16__gte", 0),
                    ("reduced_tax_base_8__gte", 0),
                    ("additional_tax_base_31__gte", 0),
                    ("igtf_tax_base__gte", 0),
                    ("exempt_internal_sales__gte", 0),
                    ("exonerated_internal_sales__gte", 0),
                    ("non_subject_internal_sales__gte", 0),
                    ("fob_export_value__gte", 0),
                ),
                name="positive_amounts",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("last_receipt_number__gte", models.F("invoice_number")),
                    ("last_receipt_number__isnull", True),
                    ("invoice_number__isnull", True),
                    _connector="OR",
                ),
                name="valid_receipt_sequence",
            ),
        ),
        migrations.AlterConstraint(
            model_name="salesrecord",
            name="unique_issued_document",
            constraint=models.UniqueConstraint(
                fields=("fiscal_profile", "control_number", "document_type"),
                name="unique_issued_document",
            ),
        ),
        migrations.AlterConstraint(
            model_name="salesrecord",
            name="zero_amount_on_annulment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("transaction_type", "03_ANNULMENT"), _negated=True),
                    ("total_sales_inc_vat", 0),
                    _connector="OR",
                ),
                name="zero_amount_on_annulment",
            ),
        ),
    ]
