# Generated by Django 6.0.7 on 2026-09-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_access", "0015_remove_salesrecord_positive_amounts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesrecord",
            name="record_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PRELIMINARY", "Preliminar"),
                    ("ANNULLED", "Anulado"),
                    ("PROCESSED", "Procesado"),
                    ("ANNULLED_PROCESSED", "Anulado_Procesado"),
                ],
                default="PRELIMINARY",
                max_length=20,
            ),
        ),
    ]
