# Generated by Django 6.0.7 on 2026-09-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_access", "0016_alter_salesrecord_record_status"),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name="salesrecord",
            name="unique_issued_document",
            constraint=models.UniqueConstraint(
                fields=("fiscal_profile", "control_number", "document_type"),
                name="unique_issued_document",
                violation_error_message="Ya existe un documento registrado con este N° de Control y Tipo de Documento para el perfil fiscal actual.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="salesrecord",
            name="zero_amount_on_annulment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("transaction_type", "03_ANNULMENT"), _negated=True),
                    ("total_sales_inc_vat", 0),
                    _connector="OR",
                ),
                name="zero_amount_on_annulment",
                violation_error_message="Para las transacciones de anulación, el monto total de ventas debe ser obligatoriamente 0.00.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="salesrecord",
            name="unique_z_report",
            constraint=models.UniqueConstraint(
                fields=(
                    "fiscal_profile",
                    "fiscal_printer_number",
                    "z_report_number",
                    "invoice_number",
                    "last_receipt_number",
                ),
                name="unique_z_report",
                violation_error_message="Este N° de Reporte Z ya fue registrado previamente para la máquina fiscal especificada.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="salesrecord",
            name="positive_amounts",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("total_sales_inc_vat__gte", 0),
                    ("general_tax_base_16__gte", 0),
                    ("reduced_tax_base_8__gte", 0),
                    ("additional_tax_base_31__gte", 0),
                    ("igtf_tax_base__gte", 0),
                    ("exempt_internal_sales__gte", 0),
                    ("exonerated_internal_sales__gte", 0),
                    ("non_subject_internal_sales__gte", 0),
                    ("fob_export_value__gte", 0),
                ),
                name="positive_amounts",
                violation_error_message="Todos los montos (ventas, bases imponibles y exenciones) deben ser mayores o iguales a 0.00.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="salesrecord",
            name="valid_receipt_sequence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("last_receipt_number__gte", models.F("invoice_number")),
                    ("last_receipt_number__isnull", True),
                    ("invoice_number__isnull", True),
                    _connector="OR",
                ),
                name="valid_receipt_sequence",
                violation_error_message="El número del último comprobante no puede ser menor al número de factura o primer comprobante.",
            ),
        ),
    ]
