# Generated by Django 6.0.7 on 2026-09-14 13:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_access", "0017_alter_salesrecord_unique_issued_document_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VatWithHolding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voucher_number",
                    models.CharField(
                        max_length=14,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El número de comprobante debe contener exactamente 14 dígitos numéricos (ejemplo: 20260500000001). Por favor, verifique el número ingresado.",
                                regex="^\\d{14}$",
                            )
                        ],
                        verbose_name="Voucher Number",
                    ),
                ),
                ("issue_date", models.DateField(verbose_name="Issue Date")),
                ("fiscal_period", models.DateField(verbose_name="Fiscal Period")),
                (
                    "client_name",
                    models.CharField(max_length=250, verbose_name="Client Name"),
                ),
                (
                    "client_rif",
                    models.CharField(max_length=20, verbose_name="Client RIF"),
                ),
                (
                    "document_number",
                    models.CharField(max_length=50, verbose_name="Document Number"),
                ),
                (
                    "control_number",
                    models.CharField(max_length=50, verbose_name="Control Number"),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Total Amount"
                    ),
                ),
                (
                    "tax_base",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Tax Base"
                    ),
                ),
                (
                    "tax_caused",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Tax Caused"
                    ),
                ),
                (
                    "withheld_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.00"),
                                message="El monto retenido no puede ser negativo. Por favor, ingrese un valor igual o mayor a cero.",
                            )
                        ],
                        verbose_name="Withheld Amount",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vat_withholdings",
                        to="data_access.customer",
                        verbose_name="Client",
                    ),
                ),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vat_withholding",
                        to="data_access.salesrecord",
                        verbose_name="Source Document",
                    ),
                ),
                (
                    "fiscal_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_models",
                        to="data_access.fiscalprofile",
                        verbose_name="Tenant / Associated Fiscal Profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "VAT Withholding",
                "verbose_name_plural": "VAT Withholdings",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("voucher_number", "client", "fiscal_profile"),
                        name="data_access_vatwithholding_unique_voucher_per_client_tenant",
                        violation_error_message="Ya existe un comprobante registrado con este número consecutivo para el cliente y perfil fiscal seleccionado. Introduzca un número distinto.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("withheld_amount__gte", Decimal("0.00"))),
                        name="data_access_vatwithholding_positive_withheld_amount",
                        violation_error_message="El monto retenido debe ser mayor o igual a cero.",
                    ),
                ],
            },
        ),
    ]
