# Generated by Django 6.0.7 on 2026-09-14 16:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_access", "0018_vatwithholding"),
    ]

    operations = [
        migrations.CreateModel(
            name="IslrWithHolding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voucher_number",
                    models.CharField(max_length=20, verbose_name="Voucher Number"),
                ),
                ("issue_date", models.DateField(verbose_name="Issue Date")),
                ("fiscal_period", models.DateField(verbose_name="Fiscal Period")),
                (
                    "client_name",
                    models.CharField(max_length=250, verbose_name="Client Name"),
                ),
                (
                    "client_rif",
                    models.CharField(max_length=20, verbose_name="Client RIF"),
                ),
                (
                    "document_number",
                    models.CharField(max_length=50, verbose_name="Document Number"),
                ),
                (
                    "control_number",
                    models.CharField(max_length=50, verbose_name="Control Number"),
                ),
                ("document_date", models.DateField(verbose_name="Document Date")),
                (
                    "seniat_code",
                    models.CharField(max_length=20, verbose_name="SENIAT Code"),
                ),
                (
                    "gross_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.01"),
                                message="El monto ingresado no puede ser negativo. Debe ser un valor mayor o igual a 0.01.",
                            )
                        ],
                        verbose_name="Gross Amount",
                    ),
                ),
                (
                    "tax_base",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.01"),
                                message="El monto ingresado no puede ser negativo. Debe ser un valor mayor o igual a 0.01.",
                            )
                        ],
                        verbose_name="Tax Base",
                    ),
                ),
                (
                    "retention_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("1.00"),
                                message="El porcentaje de retención debe estar comprendido entre el 1.00% y el 100.00%.",
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("100.00"),
                                message="El porcentaje de retención debe estar comprendido entre el 1.00% y el 100.00%.",
                            ),
                        ],
                        verbose_name="Retention Percentage",
                    ),
                ),
                (
                    "subtracting",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=20,
                        verbose_name="Subtracting",
                    ),
                ),
                (
                    "total_withheld_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.01"),
                                message="El monto ingresado no puede ser negativo. Debe ser un valor mayor o igual a 0.01.",
                            )
                        ],
                        verbose_name="Total Withheld Amount",
                    ),
                ),
                (
                    "net_amount_to_pay",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.01"),
                                message="El monto ingresado no puede ser negativo. Debe ser un valor mayor o igual a 0.01.",
                            )
                        ],
                        verbose_name="Net Amount To Pay",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="islr_withholdings",
                        to="data_access.customer",
                        verbose_name="Client",
                    ),
                ),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="islr_withholding",
                        to="data_access.salesrecord",
                        verbose_name="Document",
                    ),
                ),
                (
                    "fiscal_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_models",
                        to="data_access.fiscalprofile",
                        verbose_name="Tenant / Associated Fiscal Profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "ISLR Withholding",
                "verbose_name_plural": "ISLR Withholdings",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("fiscal_profile", "voucher_number", "client"),
                        name="unique_comprobante_per_profile",
                        violation_error_message="Ya existe un comprobante registrado con este número para el mismo cliente y perfil fiscal.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("tax_base__lte", models.F("gross_amount"))),
                        name="check_base_lte_bruto",
                        violation_error_message="Violación de integridad: La base imponible sobrepasa el monto bruto registrado.",
                    ),
                ],
            },
        ),
    ]
