# Generated by Django 6.0.7 on 2026-09-15 03:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_access", "0019_islrwithholding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="islrwithholding",
            name="retention_percentage",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal("1.00"),
                        message="El porcentaje de retención debe estar comprendido entre el 1.00%% y el 100.00%%.",
                    ),
                    django.core.validators.MaxValueValidator(
                        Decimal("100.00"),
                        message="El porcentaje de retención debe estar comprendido entre el 1.00%% y el 100.00%%.",
                    ),
                ],
                verbose_name="Retention Percentage",
            ),
        ),
        migrations.CreateModel(
            name="AccountReceivable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_period", models.DateField(verbose_name="Fiscal Period")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("PARTIALLY_PAID", "Abonada"),
                            ("PAID", "Pagada / Extinguida"),
                            ("ANNULLED", "Anulada"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "fiscal_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_models",
                        to="data_access.fiscalprofile",
                        verbose_name="Tenant / Associated Fiscal Profile",
                    ),
                ),
                (
                    "sales_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="account_receivable",
                        to="data_access.salesrecord",
                        verbose_name="Sales Record",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account Receivable",
                "verbose_name_plural": "Accounts Receivable",
            },
        ),
        migrations.CreateModel(
            name="CustomerPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_period", models.DateField(verbose_name="Fiscal Period")),
                ("payment_date", models.DateField(verbose_name="Payment Date")),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("BANK_TRANSFER", "Transferencia Bancaria"),
                            ("MOBILE_PAYMENT", "Pago Móvil"),
                            ("CASH", "Efectivo"),
                            ("POS", "Punto de Venta"),
                        ],
                        max_length=20,
                        verbose_name="Payment Method Type",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("VES", "Bolívares"),
                            ("USD", "Dólares"),
                            ("EUR", "Euros"),
                        ],
                        max_length=3,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=4, max_digits=20, verbose_name="Exchange Rate"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.01"),
                                message="El monto total del pago debe ser mayor a cero.",
                            )
                        ],
                        verbose_name="Total Amount",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Reference"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="data_access.customer",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "fiscal_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_models",
                        to="data_access.fiscalprofile",
                        verbose_name="Tenant / Associated Fiscal Profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Payment",
                "verbose_name_plural": "Customer Payments",
            },
        ),
        migrations.CreateModel(
            name="PaymentImputation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_period", models.DateField(verbose_name="Fiscal Period")),
                (
                    "imputed_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.01"),
                                message="El monto a imputar debe ser un valor positivo mayor a cero.",
                            )
                        ],
                        verbose_name="Imputed Amount",
                    ),
                ),
                (
                    "account_receivable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imputations",
                        to="data_access.accountreceivable",
                        verbose_name="Account Receivable",
                    ),
                ),
                (
                    "fiscal_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_models",
                        to="data_access.fiscalprofile",
                        verbose_name="Tenant / Associated Fiscal Profile",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imputations",
                        to="data_access.customerpayment",
                        verbose_name="Payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Imputation",
                "verbose_name_plural": "Payment Imputations",
            },
        ),
        migrations.AddConstraint(
            model_name="accountreceivable",
            constraint=models.UniqueConstraint(
                fields=("sales_record", "fiscal_profile"),
                name="unique_account_receivable_per_document_fiscal_profile",
                violation_error_message="Ya existe una cuenta por cobrar registrada para este documento de venta en el perfil fiscal activo.",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentimputation",
            constraint=models.UniqueConstraint(
                fields=("payment", "account_receivable"),
                name="unique_imputation_per_payment_and_receivable",
                violation_error_message="No se puede imputar más de una vez el mismo pago a la misma cuenta por cobrar.",
            ),
        ),
    ]
