# Generated by Django 6.0.7 on 2026-09-16 15:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_access", "0020_alter_islrwithholding_retention_percentage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerpayment",
            name="nominal_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="Nominal Value",
            ),
        ),
        migrations.AlterField(
            model_name="customerpayment",
            name="currency",
            field=models.CharField(
                choices=[("VES", "Bolívares"), ("USD", "Dólares"), ("EUR", "Euros")],
                max_length=10,
                verbose_name="Currency",
            ),
        ),
        migrations.AlterField(
            model_name="customerpayment",
            name="exchange_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("1.0000"),
                max_digits=20,
                verbose_name="Exchange Rate",
            ),
        ),
        migrations.AlterField(
            model_name="customerpayment",
            name="method_type",
            field=models.CharField(
                choices=[
                    ("BANK_TRANSFER", "Transferencia Bancaria"),
                    ("MOBILE_PAYMENT", "Pago Móvil"),
                    ("CASH", "Efectivo"),
                    ("POS", "Punto de Venta"),
                ],
                max_length=20,
                verbose_name="Payment Method",
            ),
        ),
        migrations.AlterField(
            model_name="customerpayment",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=20, verbose_name="Total Amount"
            ),
        ),
    ]
