# Generated by Django 6.0.7 on 2026-09-16 15:34

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_access", "0021_customerpayment_nominal_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerpayment",
            name="nominal_value",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.01"),
                max_digits=20,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal("0.01"),
                        message="El valor nominal debe ser mayor a cero.",
                    )
                ],
                verbose_name="Nominal Value",
            ),
        ),
    ]
