# Generated by Django 6.0.7 on 2026-09-25 19:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_access", "0023_remove_salesrecord_positive_amounts_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditNoteSettlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "settlement_type",
                    models.CharField(
                        choices=[
                            ("RETURNS", "Devoluciones"),
                            ("DISCOUNTS", "Descuentos"),
                            ("MIXED", "Mixto"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Tipo de Liquidación",
                    ),
                ),
                (
                    "returned_goods_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Valor de Bienes Devueltos",
                    ),
                ),
                (
                    "reimbursement_in_services",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Reembolso/Cancelación en Servicios",
                    ),
                ),
                (
                    "commercial_discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Monto de Descuento Comercial",
                    ),
                ),
                (
                    "bank_transfer_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Monto Transferencia Bancaria",
                    ),
                ),
                (
                    "mobile_payment_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Monto Pago Móvil",
                    ),
                ),
                (
                    "cash_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Monto Efectivo",
                    ),
                ),
                (
                    "card_pos_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Monto Punto de Venta / Tarjeta",
                    ),
                ),
                (
                    "customer_credit_balance_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Monto Reconocido como Saldo a Favor",
                    ),
                ),
                (
                    "refunded_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Total Monto Desembolsado/Reembolsado",
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Referencia de Pago",
                    ),
                ),
                (
                    "fiscal_period",
                    models.DateField(
                        blank=True, null=True, verbose_name="Período Fiscal"
                    ),
                ),
                (
                    "fiscal_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_models",
                        to="data_access.fiscalprofile",
                        verbose_name="Tenant / Associated Fiscal Profile",
                    ),
                ),
                (
                    "sales_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlement",
                        to="data_access.salesrecord",
                        verbose_name="Registro de Venta Afectado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liquidación de Nota de Crédito",
                "verbose_name_plural": "Liquidaciones de Notas de Crédito",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("returned_goods_value__gte", Decimal("0.00")),
                            ("reimbursement_in_services__gte", Decimal("0.00")),
                            ("commercial_discount_amount__gte", Decimal("0.00")),
                            ("bank_transfer_amount__gte", Decimal("0.00")),
                            ("mobile_payment_amount__gte", Decimal("0.00")),
                            ("cash_amount__gte", Decimal("0.00")),
                            ("card_pos_amount__gte", Decimal("0.00")),
                            ("customer_credit_balance_amount__gte", Decimal("0.00")),
                            ("refunded_amount__gte", Decimal("0.00")),
                        ),
                        name="non_negative_settlement_amounts",
                    ),
                    models.UniqueConstraint(
                        fields=("fiscal_profile", "sales_record"),
                        name="unique_settlement_per_sales_record",
                    ),
                ],
            },
        ),
    ]
